SHELL := /bin/bash

PLATFORM ?= linux
JOBS ?= $(shell nproc 2>/dev/null || echo 4)

SCONS := scons platform=$(PLATFORM) -j$(JOBS)
# src/rpc_gen is protoc output, regenerated by SConstruct: never format it.
FORMAT_FILES := find src -path src/rpc_gen -prune -o \( -name '*.cpp' -o -name '*.h' \) -print
# Keep in sync with CLANG_FORMAT_VERSION in .github/workflows/ci.yml: major
# versions reflow code differently, so an unpinned clang-format can pass here
# and fail in CI.
CLANG_FORMAT_VERSION := 20.1.7

.PHONY: all debug release clean submodules format format-check format-tool help

all: debug

debug: submodules
	$(SCONS) target=template_debug

release: submodules
	$(SCONS) target=template_release

submodules:
	git submodule update --init --recursive

clean:
	$(SCONS) target=template_debug -c
	$(SCONS) target=template_release -c

format-tool:
	pip install --quiet "clang-format==$(CLANG_FORMAT_VERSION)"

format: format-tool
	$(FORMAT_FILES) | xargs clang-format -i

format-check: format-tool
	$(FORMAT_FILES) | xargs clang-format --dry-run --Werror

help:
	@echo "Targets:"
	@echo "  debug         Build template_debug (default)"
	@echo "  release       Build template_release"
	@echo "  submodules    Fetch/update godot-cpp submodule"
	@echo "  clean         Remove build outputs for both targets"
	@echo "  format        Apply clang-format to src/"
	@echo "  format-check  Check formatting (as run in CI)"
	@echo ""
	@echo "Variables: PLATFORM=$(PLATFORM) JOBS=$(JOBS)"
