#include "core/proc_city_generator.h"

#include <godot_cpp/core/class_db.hpp>

using namespace godot;

void ProcCityGenerator::_bind_methods() {
	ClassDB::bind_method(D_METHOD("set_params", "params"), &ProcCityGenerator::set_params);
	ClassDB::bind_method(D_METHOD("get_params"), &ProcCityGenerator::get_params);
	ClassDB::bind_method(D_METHOD("set_mesh_size", "size"), &ProcCityGenerator::set_mesh_size);
	ClassDB::bind_method(D_METHOD("get_mesh_size"), &ProcCityGenerator::get_mesh_size);
	ClassDB::bind_method(D_METHOD("set_grid_vertices", "verts"), &ProcCityGenerator::set_grid_vertices);
	ClassDB::bind_method(D_METHOD("get_grid_vertices"), &ProcCityGenerator::get_grid_vertices);
	ClassDB::bind_method(D_METHOD("set_height_scale", "value"), &ProcCityGenerator::set_height_scale);
	ClassDB::bind_method(D_METHOD("get_height_scale"), &ProcCityGenerator::get_height_scale);
	ClassDB::bind_method(D_METHOD("set_base_height", "value"), &ProcCityGenerator::set_base_height);
	ClassDB::bind_method(D_METHOD("get_base_height"), &ProcCityGenerator::get_base_height);
	ClassDB::bind_method(D_METHOD("set_height_power", "value"), &ProcCityGenerator::set_height_power);
	ClassDB::bind_method(D_METHOD("get_height_power"), &ProcCityGenerator::get_height_power);
	ClassDB::bind_method(D_METHOD("set_block_inset", "value"), &ProcCityGenerator::set_block_inset);
	ClassDB::bind_method(D_METHOD("get_block_inset"), &ProcCityGenerator::get_block_inset);
	ClassDB::bind_method(D_METHOD("set_clip_below_height", "value"), &ProcCityGenerator::set_clip_below_height);
	ClassDB::bind_method(D_METHOD("get_clip_below_height"), &ProcCityGenerator::get_clip_below_height);
	ClassDB::bind_method(D_METHOD("set_height_image", "image"), &ProcCityGenerator::set_height_image);
	ClassDB::bind_method(D_METHOD("get_height_image"), &ProcCityGenerator::get_height_image);
	ClassDB::bind_method(D_METHOD("set_build_mode", "mode"), &ProcCityGenerator::set_build_mode);
	ClassDB::bind_method(D_METHOD("get_build_mode"), &ProcCityGenerator::get_build_mode);
	ClassDB::bind_method(D_METHOD("set_generation_mode", "mode"), &ProcCityGenerator::set_generation_mode);
	ClassDB::bind_method(D_METHOD("get_generation_mode"), &ProcCityGenerator::get_generation_mode);
	ClassDB::bind_method(D_METHOD("get_last_generation_mode_used"), &ProcCityGenerator::get_last_generation_mode_used);
	ClassDB::bind_method(D_METHOD("set_use_gpu_server", "value"), &ProcCityGenerator::set_use_gpu_server);
	ClassDB::bind_method(D_METHOD("get_use_gpu_server"), &ProcCityGenerator::get_use_gpu_server);
	ClassDB::bind_method(D_METHOD("set_sample_filter", "filter"), &ProcCityGenerator::set_sample_filter);
	ClassDB::bind_method(D_METHOD("get_sample_filter"), &ProcCityGenerator::get_sample_filter);
	ClassDB::bind_method(D_METHOD("set_max_cells", "value"), &ProcCityGenerator::set_max_cells);
	ClassDB::bind_method(D_METHOD("get_max_cells"), &ProcCityGenerator::get_max_cells);
	ClassDB::bind_method(D_METHOD("set_geometry_chunks", "value"), &ProcCityGenerator::set_geometry_chunks);
	ClassDB::bind_method(D_METHOD("get_geometry_chunks"), &ProcCityGenerator::get_geometry_chunks);
	ClassDB::bind_method(D_METHOD("set_generate_occluders", "value"), &ProcCityGenerator::set_generate_occluders);
	ClassDB::bind_method(D_METHOD("get_generate_occluders"), &ProcCityGenerator::get_generate_occluders);
	ClassDB::bind_method(D_METHOD("set_hive_warp", "value"), &ProcCityGenerator::set_hive_warp);
	ClassDB::bind_method(D_METHOD("get_hive_warp"), &ProcCityGenerator::get_hive_warp);
	ClassDB::bind_method(D_METHOD("set_hive_jitter", "value"), &ProcCityGenerator::set_hive_jitter);
	ClassDB::bind_method(D_METHOD("get_hive_jitter"), &ProcCityGenerator::get_hive_jitter);
	ClassDB::bind_method(D_METHOD("set_hive_gap", "value"), &ProcCityGenerator::set_hive_gap);
	ClassDB::bind_method(D_METHOD("get_hive_gap"), &ProcCityGenerator::get_hive_gap);
	ClassDB::bind_method(D_METHOD("set_hive_flat_rect", "value"), &ProcCityGenerator::set_hive_flat_rect);
	ClassDB::bind_method(D_METHOD("set_carve_rects", "rects"), &ProcCityGenerator::set_carve_rects);
	ClassDB::bind_method(D_METHOD("get_carve_rects"), &ProcCityGenerator::get_carve_rects);
	ClassDB::bind_method(D_METHOD("get_hive_flat_rect"), &ProcCityGenerator::get_hive_flat_rect);
	ClassDB::bind_method(D_METHOD("set_hive_rim_boost", "value"), &ProcCityGenerator::set_hive_rim_boost);
	ClassDB::bind_method(D_METHOD("get_hive_rim_boost"), &ProcCityGenerator::get_hive_rim_boost);
	ClassDB::bind_method(D_METHOD("set_hive_rim_falloff", "value"), &ProcCityGenerator::set_hive_rim_falloff);
	ClassDB::bind_method(D_METHOD("get_hive_rim_falloff"), &ProcCityGenerator::get_hive_rim_falloff);
	ClassDB::bind_method(D_METHOD("set_hive_floor", "value"), &ProcCityGenerator::set_hive_floor);
	ClassDB::bind_method(D_METHOD("get_hive_floor"), &ProcCityGenerator::get_hive_floor);
	ClassDB::bind_method(D_METHOD("set_gridmap_level_height", "value"), &ProcCityGenerator::set_gridmap_level_height);
	ClassDB::bind_method(D_METHOD("get_gridmap_level_height"), &ProcCityGenerator::get_gridmap_level_height);
	ClassDB::bind_method(D_METHOD("set_gridmap_fill_columns", "value"), &ProcCityGenerator::set_gridmap_fill_columns);
	ClassDB::bind_method(D_METHOD("get_gridmap_fill_columns"), &ProcCityGenerator::get_gridmap_fill_columns);
	ClassDB::bind_method(D_METHOD("set_gridmap_mesh_library", "library"), &ProcCityGenerator::set_gridmap_mesh_library);
	ClassDB::bind_method(D_METHOD("get_gridmap_mesh_library"), &ProcCityGenerator::get_gridmap_mesh_library);
	ClassDB::bind_method(D_METHOD("set_gridmap_item_id", "value"), &ProcCityGenerator::set_gridmap_item_id);
	ClassDB::bind_method(D_METHOD("get_gridmap_item_id"), &ProcCityGenerator::get_gridmap_item_id);
	ClassDB::bind_method(D_METHOD("set_ao_strength", "value"), &ProcCityGenerator::set_ao_strength);
	ClassDB::bind_method(D_METHOD("get_ao_strength"), &ProcCityGenerator::get_ao_strength);
	ClassDB::bind_method(D_METHOD("set_color_variation", "value"), &ProcCityGenerator::set_color_variation);
	ClassDB::bind_method(D_METHOD("get_color_variation"), &ProcCityGenerator::get_color_variation);
	ClassDB::bind_method(D_METHOD("set_material_mode", "mode"), &ProcCityGenerator::set_material_mode);
	ClassDB::bind_method(D_METHOD("get_material_mode"), &ProcCityGenerator::get_material_mode);
	ClassDB::bind_method(D_METHOD("set_texture_mode", "mode"), &ProcCityGenerator::set_texture_mode);
	ClassDB::bind_method(D_METHOD("get_texture_mode"), &ProcCityGenerator::get_texture_mode);
	ClassDB::bind_method(D_METHOD("set_normal_strength", "value"), &ProcCityGenerator::set_normal_strength);
	ClassDB::bind_method(D_METHOD("get_normal_strength"), &ProcCityGenerator::get_normal_strength);
	ClassDB::bind_method(D_METHOD("set_uv_scale", "value"), &ProcCityGenerator::set_uv_scale);
	ClassDB::bind_method(D_METHOD("get_uv_scale"), &ProcCityGenerator::get_uv_scale);
	ClassDB::bind_method(D_METHOD("set_roughness", "value"), &ProcCityGenerator::set_roughness);
	ClassDB::bind_method(D_METHOD("get_roughness"), &ProcCityGenerator::get_roughness);
	ClassDB::bind_method(D_METHOD("set_metallic", "value"), &ProcCityGenerator::set_metallic);
	ClassDB::bind_method(D_METHOD("get_metallic"), &ProcCityGenerator::get_metallic);
	ClassDB::bind_method(D_METHOD("set_texture_filter", "value"), &ProcCityGenerator::set_texture_filter);
	ClassDB::bind_method(D_METHOD("get_texture_filter"), &ProcCityGenerator::get_texture_filter);
	ClassDB::bind_method(D_METHOD("set_material_max_size", "value"), &ProcCityGenerator::set_material_max_size);
	ClassDB::bind_method(D_METHOD("get_material_max_size"), &ProcCityGenerator::get_material_max_size);
	ClassDB::bind_method(D_METHOD("set_texture_repeat", "value"), &ProcCityGenerator::set_texture_repeat);
	ClassDB::bind_method(D_METHOD("get_texture_repeat"), &ProcCityGenerator::get_texture_repeat);
	ClassDB::bind_method(D_METHOD("set_keep_intermediate_png", "value"), &ProcCityGenerator::set_keep_intermediate_png);
	ClassDB::bind_method(D_METHOD("get_keep_intermediate_png"), &ProcCityGenerator::get_keep_intermediate_png);
	ClassDB::bind_method(D_METHOD("set_persist_in_scene", "value"), &ProcCityGenerator::set_persist_in_scene);
	ClassDB::bind_method(D_METHOD("get_persist_in_scene"), &ProcCityGenerator::get_persist_in_scene);
	ClassDB::bind_method(D_METHOD("set_external_resource_dir", "value"), &ProcCityGenerator::set_external_resource_dir);
	ClassDB::bind_method(D_METHOD("get_external_resource_dir"), &ProcCityGenerator::get_external_resource_dir);
	ClassDB::bind_method(D_METHOD("set_generate_collision", "value"), &ProcCityGenerator::set_generate_collision);
	ClassDB::bind_method(D_METHOD("get_generate_collision"), &ProcCityGenerator::get_generate_collision);
	ClassDB::bind_method(D_METHOD("set_collision_layer", "value"), &ProcCityGenerator::set_collision_layer);
	ClassDB::bind_method(D_METHOD("get_collision_layer"), &ProcCityGenerator::get_collision_layer);
	ClassDB::bind_method(D_METHOD("set_auto_download_binary", "value"), &ProcCityGenerator::set_auto_download_binary);
	ClassDB::bind_method(D_METHOD("get_auto_download_binary"), &ProcCityGenerator::get_auto_download_binary);
	ClassDB::bind_method(D_METHOD("set_binary_path_override", "value"), &ProcCityGenerator::set_binary_path_override);
	ClassDB::bind_method(D_METHOD("get_binary_path_override"), &ProcCityGenerator::get_binary_path_override);
	ClassDB::bind_method(D_METHOD("set_output_dir", "value"), &ProcCityGenerator::set_output_dir);
	ClassDB::bind_method(D_METHOD("get_output_dir"), &ProcCityGenerator::get_output_dir);

	ClassDB::bind_method(D_METHOD("generate_displacement"), &ProcCityGenerator::generate_displacement);
	ClassDB::bind_method(D_METHOD("build_geometry"), &ProcCityGenerator::build_geometry);
	ClassDB::bind_method(D_METHOD("generate_material"), &ProcCityGenerator::generate_material);
	ClassDB::bind_method(D_METHOD("generate_all"), &ProcCityGenerator::generate_all);
	ClassDB::bind_method(D_METHOD("randomize_palette"), &ProcCityGenerator::randomize_palette);
	ClassDB::bind_method(D_METHOD("clear_generated"), &ProcCityGenerator::clear_generated);
	ClassDB::bind_method(D_METHOD("is_busy"), &ProcCityGenerator::is_busy);
	ClassDB::bind_method(D_METHOD("get_cell_heights"), &ProcCityGenerator::get_cell_heights);
	ClassDB::bind_method(D_METHOD("sample_city_height", "local_point"), &ProcCityGenerator::sample_city_height);
	ClassDB::bind_method(D_METHOD("is_point_inside_block", "local_point"), &ProcCityGenerator::is_point_inside_block);
	ClassDB::bind_method(D_METHOD("find_clear_point", "local_point", "max_radius"), &ProcCityGenerator::find_clear_point);
	ClassDB::bind_method(D_METHOD("release_source_images"), &ProcCityGenerator::release_source_images);
	ClassDB::bind_method(D_METHOD("externalize_generated_resources"), &ProcCityGenerator::externalize_generated_resources);

	ClassDB::bind_method(D_METHOD("_thread_body", "job"), &ProcCityGenerator::_thread_body);
	ClassDB::bind_method(D_METHOD("_apply_results", "result"), &ProcCityGenerator::_apply_results);
	ClassDB::bind_method(D_METHOD("_emit_failed", "stage", "message"), &ProcCityGenerator::_emit_failed);

	ClassDB::bind_method(D_METHOD("_btn_generate_displacement"), &ProcCityGenerator::_btn_generate_displacement);
	ClassDB::bind_method(D_METHOD("_btn_build_geometry"), &ProcCityGenerator::_btn_build_geometry);
	ClassDB::bind_method(D_METHOD("_btn_generate_material"), &ProcCityGenerator::_btn_generate_material);
	ClassDB::bind_method(D_METHOD("_btn_generate_all"), &ProcCityGenerator::_btn_generate_all);
	ClassDB::bind_method(D_METHOD("_btn_randomize_palette"), &ProcCityGenerator::_btn_randomize_palette);
	ClassDB::bind_method(D_METHOD("_btn_clear_generated"), &ProcCityGenerator::_btn_clear_generated);
	_bind_inspector_surface();
}
